"""create_file_records_table

Revision ID: 3232e4a5533a
Revises: fda5b75141d5
Create Date: 2025-09-17 12:14:59.382092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import fastapi_users_db_sqlalchemy.generics


# revision identifiers, used by Alembic.
revision: str = '3232e4a5533a'
down_revision: Union[str, Sequence[str], None] = 'fda5b75141d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_records',
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.Enum('AVATAR', 'DOCUMENT', name='filetype'), nullable=False),
    sa.Column('s3_key', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('UPLOADING', 'ACTIVE', 'PROCESSING', 'ERROR', 'DELETED', name='filestatus'), nullable=False),
    sa.Column('uploaded_by', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('file_metadata', sa.JSON(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_file_records_file_hash'), 'file_records', ['file_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_records_file_hash'), table_name='file_records')
    op.drop_table('file_records')
    # ### end Alembic commands ###
