"""add_input_output_tokens_to_conversations

Revision ID: 640b988b2062
Revises: b10fb7b3416c
Create Date: 2025-11-05 09:22:34.410260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import fastapi_users_db_sqlalchemy.generics


# revision identifiers, used by Alembic.
revision: str = '640b988b2062'
down_revision: Union[str, Sequence[str], None] = 'b10fb7b3416c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_tokens', sa.Integer(), nullable=True, comment='Total input tokens used in this conversation'))
        batch_op.add_column(sa.Column('output_tokens', sa.Integer(), nullable=True, comment='Total output tokens used in this conversation'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('output_tokens')
        batch_op.drop_column('input_tokens')

    # ### end Alembic commands ###
