"""add_usage_count_to_assistants

Revision ID: 7f768f23f8b3
Revises: 75b8e8b450ab
Create Date: 2025-10-16 05:42:34.940133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import fastapi_users_db_sqlalchemy.generics


# revision identifiers, used by Alembic.
revision: str = '7f768f23f8b3'
down_revision: Union[str, Sequence[str], None] = '75b8e8b450ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usage_count', sa.Integer(), server_default='0', nullable=False, comment='Number of times this assistant has been used'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistants', schema=None) as batch_op:
        batch_op.drop_column('usage_count')

    # ### end Alembic commands ###
