"""add_translations_to_assistants

Revision ID: 103ceb0be266
Revises: abd5dbbceb93
Create Date: 2025-11-13 06:09:10.402945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import fastapi_users_db_sqlalchemy.generics


# revision identifiers, used by Alembic.
revision: str = '103ceb0be266'
down_revision: Union[str, Sequence[str], None] = 'abd5dbbceb93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('translations', sa.JSON(), nullable=True, comment='Multi-language translations for name, description, and system_prompt'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistants', schema=None) as batch_op:
        batch_op.drop_column('translations')

    # ### end Alembic commands ###
