"""add_agent_to_assistant

Revision ID: 22b6ce8c41bf
Revises: 7f768f23f8b3
Create Date: 2025-10-17 03:01:16.402395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import fastapi_users_db_sqlalchemy.generics


# revision identifiers, used by Alembic.
revision: str = '22b6ce8c41bf'
down_revision: Union[str, Sequence[str], None] = '7f768f23f8b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mcp_servers',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('server_type', sa.Enum('STDIO', 'SSE', 'HTTP', name='mcpservertypeenum'), nullable=False),
    sa.Column('connection_config', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mcp_servers')),
    sa.UniqueConstraint('name', name=op.f('uq_mcp_servers_name'))
    )
    op.create_table('assistant_mcp_servers',
    sa.Column('assistant_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('mcp_server_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.id'], name=op.f('fk_assistant_mcp_servers_assistant_id_assistants'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['mcp_server_id'], ['mcp_servers.id'], name=op.f('fk_assistant_mcp_servers_mcp_server_id_mcp_servers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('assistant_id', 'mcp_server_id', name=op.f('pk_assistant_mcp_servers'))
    )
    op.create_table('agent_executions',
    sa.Column('conversation_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('input_text', sa.Text(), nullable=False),
    sa.Column('output_text', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', 'TIMEOUT', name='agentexecutionstatusenum'), nullable=False),
    sa.Column('thought_chain', sa.JSON(), nullable=False),
    sa.Column('token_usage', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_agent_executions_conversation_id_conversations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_executions'))
    )
    with op.batch_alter_table('assistants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enable_agent', sa.Boolean(), server_default='false', nullable=False, comment='Whether to enable agent (tool calling) capabilities'))
        batch_op.add_column(sa.Column('agent_max_iterations', sa.Integer(), server_default='5', nullable=False, comment='Maximum iterations for agent reasoning'))
        batch_op.add_column(sa.Column('agent_enabled_tools', sa.JSON(), server_default='[]', nullable=False, comment='List of enabled tool names for agent'))
        batch_op.add_column(sa.Column('agent_tool_config', sa.JSON(), server_default='{}', nullable=False, comment='Tool configuration parameters for agent'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistants', schema=None) as batch_op:
        batch_op.drop_column('agent_tool_config')
        batch_op.drop_column('agent_enabled_tools')
        batch_op.drop_column('agent_max_iterations')
        batch_op.drop_column('enable_agent')

    op.drop_table('agent_executions')
    op.drop_table('assistant_mcp_servers')
    op.drop_table('mcp_servers')
    # ### end Alembic commands ###
