"""add email rate limit timestamps to users table

Revision ID: ac1aeb929adb
Revises: b10fb7b3416c
Create Date: 2025-11-07 08:05:25.832834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import fastapi_users_db_sqlalchemy.generics


# revision identifiers, used by Alembic.
revision: str = 'ac1aeb929adb'
down_revision: Union[str, Sequence[str], None] = 'b10fb7b3416c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_verification_email_sent_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('last_password_reset_email_sent_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_password_reset_email_sent_at')
        batch_op.drop_column('last_verification_email_sent_at')

    # ### end Alembic commands ###
