"""add_temperature_to_assistant

Revision ID: f958365bebd5
Revises: 90693c660d8f
Create Date: 2025-09-23 01:32:04.765457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import fastapi_users_db_sqlalchemy.generics


# revision identifiers, used by Alembic.
revision: str = 'f958365bebd5'
down_revision: Union[str, Sequence[str], None] = '90693c660d8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperature', sa.Float(), server_default='1.0', nullable=False, comment='Temperature for text generation (0.0-2.0)'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistants', schema=None) as batch_op:
        batch_op.drop_column('temperature')

    # ### end Alembic commands ###
