"""add_category_and_tags_to_assistants

Revision ID: 6ea1e26ac6c3
Revises: 5860726530bc
Create Date: 2025-11-25 03:02:16.764524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import fastapi_users_db_sqlalchemy.generics


# revision identifiers, used by Alembic.
revision: str = '6ea1e26ac6c3'
down_revision: Union[str, Sequence[str], None] = '5860726530bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True, comment='Primary category of the assistant'))
        batch_op.add_column(sa.Column('tags', sa.JSON(), server_default='[]', nullable=False, comment='List of tags for filtering'))
        batch_op.create_index(batch_op.f('ix_assistants_category'), ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistants_category'))
        batch_op.drop_column('tags')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
