"""add conversation shares table

Revision ID: 948d2d59c1b8
Revises: 103ceb0be266
Create Date: 2025-11-19 07:02:05.216641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import fastapi_users_db_sqlalchemy.generics


# revision identifiers, used by Alembic.
revision: str = '948d2d59c1b8'
down_revision: Union[str, Sequence[str], None] = '103ceb0be266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conversation_shares',
    sa.Column('conversation_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('created_by', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('scope', sa.Enum('CONVERSATION', 'MESSAGE', name='conversationsharescopeenum'), nullable=False),
    sa.Column('start_message_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('end_message_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', name='conversationsharestatusenum'), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_conversation_shares_conversation_id_conversations'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_conversation_shares_created_by_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['end_message_id'], ['messages.id'], name=op.f('fk_conversation_shares_end_message_id_messages'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['start_message_id'], ['messages.id'], name=op.f('fk_conversation_shares_start_message_id_messages'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversation_shares'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('conversation_shares')
    # ### end Alembic commands ###
