"""add_assistant_knowledge_base

Revision ID: 90693c660d8f
Revises: 3d4d8a47e4e6
Create Date: 2025-09-21 11:53:36.568934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import fastapi_users_db_sqlalchemy.generics


# revision identifiers, used by Alembic.
revision: str = '90693c660d8f'
down_revision: Union[str, Sequence[str], None] = '3d4d8a47e4e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rag_config', sa.JSON(), nullable=False))
        batch_op.add_column(sa.Column('knowledge_base_ids', sa.JSON(), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistants', schema=None) as batch_op:
        batch_op.drop_column('knowledge_base_ids')
        batch_op.drop_column('rag_config')

    # ### end Alembic commands ###
