"""add_oauth_tables

Revision ID: 7c09e537d986
Revises: f125f7fdc415
Create Date: 2025-09-28 02:20:04.962330

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import fastapi_users_db_sqlalchemy.generics


# revision identifiers, used by Alembic.
revision: str = '7c09e537d986'
down_revision: Union[str, Sequence[str], None] = 'f125f7fdc415'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_providers',
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('client_id', sa.String(length=500), nullable=False),
    sa.Column('client_secret', sa.String(length=1000), nullable=False),
    sa.Column('auth_url', sa.String(length=1000), nullable=False),
    sa.Column('token_url', sa.String(length=1000), nullable=False),
    sa.Column('user_info_url', sa.String(length=1000), nullable=False),
    sa.Column('scopes', sa.JSON(), nullable=False),
    sa.Column('user_mapping', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('icon_url', sa.String(length=500), nullable=True),
    sa.Column('button_color', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_providers')),
    sa.UniqueConstraint('name', name=op.f('uq_oauth_providers_name'))
    )
    op.create_table('oauth_states',
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('provider_name', sa.String(length=100), nullable=False),
    sa.Column('redirect_uri', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_states')),
    sa.UniqueConstraint('state', name=op.f('uq_oauth_states_state'))
    )
    op.create_table('oauth_user_links',
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('provider_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('provider_user_id', sa.String(length=500), nullable=False),
    sa.Column('provider_username', sa.String(length=200), nullable=True),
    sa.Column('provider_email', sa.String(length=320), nullable=True),
    sa.Column('provider_avatar', sa.String(length=1000), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_user_info', sa.JSON(), nullable=True),
    sa.Column('linked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['oauth_providers.id'], name=op.f('fk_oauth_user_links_provider_id_oauth_providers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_oauth_user_links_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_oauth_user_links')),
    sa.UniqueConstraint('provider_id', 'provider_user_id', name='unique_provider_user'),
    sa.UniqueConstraint('user_id', 'provider_id', name='unique_user_provider')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('oauth_user_links')
    op.drop_table('oauth_states')
    op.drop_table('oauth_providers')
    # ### end Alembic commands ###
