"""add generation config to models

Revision ID: b08ed6ca3c5e
Revises: 948d2d59c1b8
Create Date: 2025-11-22 10:07:08.865059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import fastapi_users_db_sqlalchemy.generics


# revision identifiers, used by Alembic.
revision: str = 'b08ed6ca3c5e'
down_revision: Union[str, Sequence[str], None] = '948d2d59c1b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('generation_config', sa.JSON(), server_default='{}', nullable=False, comment='Provider-specific generation parameters'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('models', schema=None) as batch_op:
        batch_op.drop_column('generation_config')

    # ### end Alembic commands ###
