"""rename_model_config_to_config

Revision ID: 9331e7620e25
Revises: 0c8e2d4ce139
Create Date: 2025-09-13 03:09:58.950987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import fastapi_users_db_sqlalchemy.generics
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '9331e7620e25'
down_revision: Union[str, Sequence[str], None] = '0c8e2d4ce139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('config', sa.JSON(), nullable=False))
    op.drop_column('assistants', 'model_config')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assistants', sa.Column('model_config', sqlite.JSON(), nullable=False))
    op.drop_column('assistants', 'config')
    # ### end Alembic commands ###
