"""remove_name_from_model_provider

Revision ID: bee48c0c34e2
Revises: 9fe2d9484baa
Create Date: 2025-12-31 14:44:10.536557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import fastapi_users_db_sqlalchemy.generics


# revision identifiers, used by Alembic.
revision: str = 'bee48c0c34e2'
down_revision: Union[str, Sequence[str], None] = '9fe2d9484baa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.drop_column('input_tokens')
        batch_op.drop_column('output_tokens')

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_column('token_count')

    with op.batch_alter_table('model_providers', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_model_providers_name'), type_='unique')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=100), nullable=False))
        batch_op.create_unique_constraint(batch_op.f('uq_model_providers_name'), ['name'])

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_count', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('conversations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('output_tokens', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('input_tokens', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
