"""modify_s3_key_to_file_path_in_file_records_table

Revision ID: f868e86c1da8
Revises: 3232e4a5533a
Create Date: 2025-09-18 06:38:15.258424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import fastapi_users_db_sqlalchemy.generics


# revision identifiers, used by Alembic.
revision: str = 'f868e86c1da8'
down_revision: Union[str, Sequence[str], None] = '3232e4a5533a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_file_path', sa.String(length=1000), nullable=True))
        batch_op.drop_column('avatar_url')

    with op.batch_alter_table('file_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_path', sa.String(length=1000), nullable=True))
        batch_op.drop_column('s3_key')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('s3_key', sa.VARCHAR(length=1000), nullable=True))
        batch_op.drop_column('file_path')

    with op.batch_alter_table('assistants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.VARCHAR(length=500), nullable=True))
        batch_op.drop_column('avatar_file_path')

    # ### end Alembic commands ###
