"""change_filetype_to_string

Revision ID: 5860726530bc
Revises: b08ed6ca3c5e
Create Date: 2025-11-22 16:23:09.086301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import fastapi_users_db_sqlalchemy.generics
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5860726530bc'
down_revision: Union[str, Sequence[str], None] = 'b08ed6ca3c5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_records', schema=None) as batch_op:
        batch_op.alter_column('file_type',
               existing_type=postgresql.ENUM('AVATAR', 'DOCUMENT', name='filetype'),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('UPLOADING', 'ACTIVE', 'PROCESSING', 'ERROR', 'DELETED', name='filestatus'),
               type_=sa.String(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_records', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('UPLOADING', 'ACTIVE', 'PROCESSING', 'ERROR', 'DELETED', name='filestatus'),
               existing_nullable=False)
        batch_op.alter_column('file_type',
               existing_type=sa.String(length=50),
               type_=postgresql.ENUM('AVATAR', 'DOCUMENT', name='filetype'),
               existing_nullable=False)

    # ### end Alembic commands ###
