"""add_max_history_messages_to_assistant

Revision ID: 2352448f1649
Revises: 4876f0e893dd
Create Date: 2025-09-25 10:11:41.421222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import fastapi_users_db_sqlalchemy.generics


# revision identifiers, used by Alembic.
revision: str = '2352448f1649'
down_revision: Union[str, Sequence[str], None] = '4876f0e893dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_history_messages', sa.Integer(), nullable=True, comment='Maximum number of history messages to include in context'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistants', schema=None) as batch_op:
        batch_op.drop_column('max_history_messages')

    # ### end Alembic commands ###
