"""add_max_tokens_to_assistants

Revision ID: a71a75ba6919
Revises: 6ea1e26ac6c3
Create Date: 2025-11-25 04:26:32.855921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import fastapi_users_db_sqlalchemy.generics


# revision identifiers, used by Alembic.
revision: str = 'a71a75ba6919'
down_revision: Union[str, Sequence[str], None] = '6ea1e26ac6c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('max_tokens', sa.Integer(), server_default='2048', nullable=False, comment='Maximum number of tokens to generate'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistants', schema=None) as batch_op:
        batch_op.drop_column('max_tokens')

    # ### end Alembic commands ###
