"""create_system_configs_table

Revision ID: 0baa2d826f9a
Revises: 05837c9ba677
Create Date: 2025-09-12 07:01:03.811760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import fastapi_users_db_sqlalchemy.generics


# revision identifiers, used by Alembic.
revision: str = '0baa2d826f9a'
down_revision: Union[str, Sequence[str], None] = '05837c9ba677'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_configs',
    sa.Column('key', sa.String(length=255), nullable=False, comment='Configuration key name'),
    sa.Column('value', sa.Text(), nullable=False, comment='Configuration value (JSON format)'),
    sa.Column('description', sa.Text(), nullable=True, comment='Configuration description'),
    sa.Column('is_public', sa.Boolean(), nullable=False, comment='Whether this is a public configuration'),
    sa.Column('is_enabled', sa.Boolean(), nullable=False, comment='Whether this configuration item is enabled'),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configs_key'), 'system_configs', ['key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_configs_key'), table_name='system_configs')
    op.drop_table('system_configs')
    # ### end Alembic commands ###
