"""create_assistant_channels_table

Revision ID: b3bace30b8b0
Revises: 1d36e54194d7
Create Date: 2026-01-09 11:01:12.681235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import fastapi_users_db_sqlalchemy.generics


# revision identifiers, used by Alembic.
revision: str = 'b3bace30b8b0'
down_revision: Union[str, Sequence[str], None] = '1d36e54194d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_channels',
    sa.Column('assistant_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('credentials', sa.JSON(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.id'], name=op.f('fk_assistant_channels_assistant_id_assistants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assistant_channels'))
    )
    with op.batch_alter_table('assistant_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assistant_channels_assistant_id'), ['assistant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistant_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistant_channels_assistant_id'))

    op.drop_table('assistant_channels')
    # ### end Alembic commands ###
