"""create scheduled_task_executions table

Revision ID: fa5a92a2fcb7
Revises: a2e4cf140a81
Create Date: 2026-01-27 13:57:46.932320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import fastapi_users_db_sqlalchemy.generics


# revision identifiers, used by Alembic.
revision: str = 'fa5a92a2fcb7'
down_revision: Union[str, Sequence[str], None] = 'a2e4cf140a81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_task_executions',
    sa.Column('task_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration', sa.String(length=50), nullable=True),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['scheduled_tasks.id'], name=op.f('fk_scheduled_task_executions_task_id_scheduled_tasks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_task_executions'))
    )
    with op.batch_alter_table('scheduled_task_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_task_executions_task_id'), ['task_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_task_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_task_executions_task_id'))

    op.drop_table('scheduled_task_executions')
    # ### end Alembic commands ###
