"""add_timezone_to_scheduled_tasks

Revision ID: 9876543210ab
Revises: 33fcf364a34b
Create Date: 2026-02-05 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9876543210ab'
down_revision: Union[str, Sequence[str], None] = '33fcf364a34b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), server_default='UTC', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_tasks', schema=None) as batch_op:
        batch_op.drop_column('timezone')
    # ### end Alembic commands ###
