"""add_model_parameters_to_assistant

Revision ID: 33fcf364a34b
Revises: fa5a92a2fcb7
Create Date: 2026-01-29 14:40:49.914426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import fastapi_users_db_sqlalchemy.generics


# revision identifiers, used by Alembic.
revision: str = '33fcf364a34b'
down_revision: Union[str, Sequence[str], None] = 'fa5a92a2fcb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_parameters', sa.JSON(), server_default='{}', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistants', schema=None) as batch_op:
        batch_op.drop_column('model_parameters')

    # ### end Alembic commands ###
