"""refactor_channels_rename_tables

Revision ID: 8ac4b6577aeb
Revises: 075dbc4464a0
Create Date: 2026-01-25 13:00:01.368008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import fastapi_users_db_sqlalchemy.generics
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '8ac4b6577aeb'
down_revision: Union[str, Sequence[str], None] = '075dbc4464a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_configs',
    sa.Column('owner_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('assistant_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('credentials', sa.JSON(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.id'], name=op.f('fk_channel_configs_assistant_id_assistants'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_channel_configs_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_configs'))
    )
    with op.batch_alter_table('channel_configs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_configs_assistant_id'), ['assistant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_configs_owner_id'), ['owner_id'], unique=False)

    op.create_table('user_channel_bindings',
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('channel_config_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('external_user_id', sa.String(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_config_id'], ['channel_configs.id'], name=op.f('fk_user_channel_bindings_channel_config_id_channel_configs'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_channel_bindings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_channel_bindings')),
    sa.UniqueConstraint('provider', 'external_user_id', name='uq_provider_external_user')
    )
    with op.batch_alter_table('user_channel_bindings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_channel_bindings_external_user_id'), ['external_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_channel_bindings_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('assistant_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assistant_channels_assistant_id'))

    op.drop_table('assistant_channels')
    with op.batch_alter_table('channel_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_identities_identity_id'))
        batch_op.drop_index(batch_op.f('ix_channel_identities_user_id'))

    op.drop_table('channel_identities')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_identities',
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('channel_id', sa.CHAR(length=36), nullable=True),
    sa.Column('provider', sa.VARCHAR(), nullable=False),
    sa.Column('identity_id', sa.VARCHAR(), nullable=False),
    sa.Column('extra_data', sqlite.JSON(), nullable=False),
    sa.Column('last_seen_at', sa.DATETIME(), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['assistant_channels.id'], name=op.f('fk_channel_identities_channel_id_assistant_channels'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_channel_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_identities')),
    sa.UniqueConstraint('provider', 'identity_id', name=op.f('uq_provider_identity'))
    )
    with op.batch_alter_table('channel_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_identities_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_identities_identity_id'), ['identity_id'], unique=False)

    op.create_table('assistant_channels',
    sa.Column('assistant_id', sa.CHAR(length=36), nullable=False),
    sa.Column('provider', sa.VARCHAR(), nullable=False),
    sa.Column('name', sa.VARCHAR(), nullable=False),
    sa.Column('credentials', sqlite.JSON(), nullable=False),
    sa.Column('settings', sqlite.JSON(), nullable=False),
    sa.Column('metadata', sqlite.JSON(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.id'], name=op.f('fk_assistant_channels_assistant_id_assistants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assistant_channels'))
    )
    with op.batch_alter_table('assistant_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assistant_channels_assistant_id'), ['assistant_id'], unique=False)

    with op.batch_alter_table('user_channel_bindings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_channel_bindings_user_id'))
        batch_op.drop_index(batch_op.f('ix_user_channel_bindings_external_user_id'))

    op.drop_table('user_channel_bindings')
    with op.batch_alter_table('channel_configs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_configs_owner_id'))
        batch_op.drop_index(batch_op.f('ix_channel_configs_assistant_id'))

    op.drop_table('channel_configs')
    # ### end Alembic commands ###
