"""add_metadata_to_system_config

Revision ID: 3b7601fb020b
Revises: bee48c0c34e2
Create Date: 2026-01-05 11:51:11.869584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import fastapi_users_db_sqlalchemy.generics


# revision identifiers, used by Alembic.
revision: str = '3b7601fb020b'
down_revision: Union[str, Sequence[str], None] = 'bee48c0c34e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config_type', sa.String(length=50), server_default='text', nullable=False, comment='UI component type (text, boolean, number, select, image, etc.)'))
        batch_op.add_column(sa.Column('config_group', sa.String(length=50), server_default='general', nullable=False, comment='Configuration group for UI grouping'))
        batch_op.add_column(sa.Column('label', sa.String(length=255), nullable=True, comment='Display label for UI'))
        batch_op.add_column(sa.Column('options', sa.Text(), nullable=True, comment='Options for select type (JSON format)'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_configs', schema=None) as batch_op:
        batch_op.drop_column('options')
        batch_op.drop_column('label')
        batch_op.drop_column('config_group')
        batch_op.drop_column('config_type')

    # ### end Alembic commands ###
