"""add_scheduled_tasks

Revision ID: c8d779fd862a
Revises: 8ac4b6577aeb
Create Date: 2026-01-25 13:25:13.556237

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import fastapi_users_db_sqlalchemy.generics


# revision identifiers, used by Alembic.
revision: str = 'c8d779fd862a'
down_revision: Union[str, Sequence[str], None] = '8ac4b6577aeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scheduled_tasks',
    sa.Column('owner_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('cron_expression', sa.String(length=100), nullable=False),
    sa.Column('assistant_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('prompt_template', sa.Text(), nullable=False),
    sa.Column('target_binding_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assistant_id'], ['assistants.id'], name=op.f('fk_scheduled_tasks_assistant_id_assistants'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_scheduled_tasks_owner_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_binding_id'], ['user_channel_bindings.id'], name=op.f('fk_scheduled_tasks_target_binding_id_user_channel_bindings'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scheduled_tasks'))
    )
    with op.batch_alter_table('scheduled_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_tasks_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_tasks_owner_id'))

    op.drop_table('scheduled_tasks')
    # ### end Alembic commands ###
