"""create_channel_identities_table

Revision ID: 075dbc4464a0
Revises: b3bace30b8b0
Create Date: 2026-01-11 19:54:44.026583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import fastapi_users_db_sqlalchemy.generics


# revision identifiers, used by Alembic.
revision: str = '075dbc4464a0'
down_revision: Union[str, Sequence[str], None] = 'b3bace30b8b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('channel_identities',
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('channel_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('identity_id', sa.String(), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['assistant_channels.id'], name=op.f('fk_channel_identities_channel_id_assistant_channels'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_channel_identities_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_channel_identities')),
    sa.UniqueConstraint('provider', 'identity_id', name='uq_provider_identity')
    )
    with op.batch_alter_table('channel_identities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_channel_identities_identity_id'), ['identity_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_channel_identities_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('channel_identities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_channel_identities_user_id'))
        batch_op.drop_index(batch_op.f('ix_channel_identities_identity_id'))

    op.drop_table('channel_identities')
    # ### end Alembic commands ###
