"""refactor_scheduled_tasks_target

Revision ID: a2e4cf140a81
Revises: c8d779fd862a
Create Date: 2026-01-26 16:17:34.818889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import fastapi_users_db_sqlalchemy.generics


# revision identifiers, used by Alembic.
revision: str = 'a2e4cf140a81'
down_revision: Union[str, Sequence[str], None] = 'c8d779fd862a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('channel_config_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False))
        batch_op.add_column(sa.Column('target_identifier', sa.String(length=255), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_scheduled_tasks_target_binding_id_user_channel_bindings'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_scheduled_tasks_channel_config_id_channel_configs'), 'channel_configs', ['channel_config_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('target_binding_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scheduled_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_binding_id', sa.CHAR(length=36), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_scheduled_tasks_channel_config_id_channel_configs'), type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_scheduled_tasks_target_binding_id_user_channel_bindings'), 'user_channel_bindings', ['target_binding_id'], ['id'], ondelete='RESTRICT')
        batch_op.drop_column('target_identifier')
        batch_op.drop_column('channel_config_id')

    # ### end Alembic commands ###
